# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  # コンテナ落として全て削除
  clean:
    cmds:
      - docker compose down --remove-orphans --rmi all --volumes
    silent: true

  # 初回セットアップ
  setup:
    cmds:
      - task: genkey
      - task: up
  
  up:
    cmds:
      - docker compose up -d --build
  
  genkey:
    cmds:
      - cmd: docker run --rm -it -v .\\openssl\\jwtKeys:/jwtkeys -v .\\nginx\\keys:/sslkeys {{.Build_Image}}
        platforms: [windows]
      - cmd: docker run --rm -it -v ./openssl/jwtKeys:/jwtkeys -v ./nginx/keys:/sslkeys {{.Build_Image}}
        platforms: [linux,darwin]
    vars:
      Build_Image:
        sh: docker build -q ./openssl